[package]
name = "raidar"
version = "0.1.0"
authors = ["Dzmitry Talkach <chakmidlot@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
chrono = "0.4.19"
tempdir = "0.3.7"
